---

name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Virtualbox
        run: sudo apt-get update && sudo apt-get install virtualbox -y
      
      - name: Extend Path
        run: sudo ln -s /usr/lib/virtualbox/VBoxManage /usr/local/bin/VBoxManage

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix
          target: kali-linux-2.0-amd64-desktop.json

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: kali-linux-2.0-amd64-desktop.json

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: kali-linux-2.0-amd64-desktop.json
        env:
          PACKER_LOG: 1