---

name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Virtualbox
        run: sudo apt-get update && sudo apt-get install virtualbox -y

      - name: Install packer
        run: sudo apt-get install packer -y
      
      - name: Extend Path
        run: sudo ln -s /usr/lib/virtualbox/VBoxManage /usr/local/bin/VBoxManage
      
      - name: Run packer validate
        run: packer validate -syntax-only .

      - name: Run packer validate
        run: packer build -color=false -on-error=abort kali-linux-2.0-amd64-desktop.json
